apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:22.0.4
        env:
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        # NOTE this initial admin can only be used on first boot.
        # In fact, Keycloak will create it in its DB only if it isn't
        # there already. So the second time this pod restarts the user
        # will be there and changing the password through the below env
        # var will have no effect---you'll have to log onto Keycloak to
        # change it. This is why we're not asking Reloader to monitor
        # changes to this pod's linked secret.
        #- name: KEYCLOAK_USER
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keycloak-builtin-admin
              key: username
        #- name: KEYCLOAK_PASSWORD
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-builtin-admin
              key: password
        - name: DB_VENDOR
          value: "h2"
        - name: KC_PROXY
          value: "edge"
        - name: KEYCLOAK_HTTP_RELATIVE_PATH
          value: /auth
        - name: KC_HOSTNAME
          value: resonance.collab-cloud.eu
        - name: KEYCLOAK_HOSTNAME_STRICT
          value: "false"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
        volumeMounts:
        - name: h2-volume
          mountPath: /opt/jboss/keycloak/standalone/data
        #command: ["/opt/keycloak/bin/kc.sh", "start-dev"]
        args: ["start-dev","--http-relative-path /auth","--auto-build"]
      volumes:
      - name: h2-volume
        persistentVolumeClaim:
          claimName: keycloak-pvc
