apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
data:
  allow-snippet-annotations: "false"
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      folder: istio
      name: istio
      options:
        path: /var/lib/grafana/dashboards/istio
      orgId: 1
      type: file
    - disableDeletion: false
      folder: istio
      name: istio-services
      options:
        path: /var/lib/grafana/dashboards/istio-services
      orgId: 1
      type: file
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: Prometheus
      orgId: 1
      type: prometheus
      url: http://prometheus:9090
    - access: proxy
      editable: true
      isDefault: false
      jsonData:
        timeInterval: 5s
      name: Loki
      orgId: 1
      type: loki
      url: http://loki:3100
  grafana.ini: |
    [server]
    root_url = https://resonance.collab-cloud.eu/grafana/
    cookie_secure = true
    cookie_samesite = lax
    serve_from_sub_path = false
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    level = debug
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [auth.generic_oauth]
    enabled = true
    root_url = https://resonance.collab-cloud.eu/grafana/
    log.level = debug
    name = Keycloak-OAuth
    allow_sign_up = true
    client_id = grafana
    client_secret = BQftuYsXcc9BTqZRFTyZqPQsn7IlcsNO
    scopes = openid email profile offline_access roles
    email_attribute_path = email
    login_attribute_path = username
    name_attribute_path = full_name
    auth_url = https://resonance.collab-cloud.eu/auth/realms/master/protocol/openid-connect/auth
    token_url = https://resonance.collab-cloud.eu/auth/realms/master/protocol/openid-connect/token
    api_url = https://resonance.collab-cloud.eu/auth/realms/master/protocol/openid-connect/userinfo
    role_attribute_path = realm_access.roles
